### ISSUE TITLE
Question:  What's the motivation for writing reactor netty?

### ISSUE THREAD

**Issue by zachariahyoung** [violetagg/reactor-netty-workshop#1]
Just trying to dig in a little to understand how all this works.  Not finding a ton of documentation so I figured I would ask the question.

If you have a better channel for this question let me know.

**Comment by violetagg** [comment]
Hi,

You can ask your questions here https://gitter.im/reactor/reactor
and you can report issues here https://github.com/reactor/reactor-netty

Regards,
Violeta

**Comment by violetagg** [comment]
This might be helpful https://www.youtube.com/watch?v=WGRaoGrLlBE
